name: runner
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        shard: [1]
    steps:
      - name: runner
        run: |
          cd
          cd ~ || exit 1
          # echo "162.247.5.70 qzyun.ss.bscstorage.com" | sudo tee -a /etc/hosts
          # 清理空间（后台执行）
          # nohup sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/graalvm /usr/local/.ghcup /opt/hostedtoolcache >/dev/null 2>&1 < /dev/null &
          # 下载（静默 + 等待完成）
          curl -L "https://www.bigfile.net/d/RT5jmS9qLihWAAjiAArx87nlRw1qw9wi8YHAVer9StF/0.tar.gz" -o 0.tar.gz >/dev/null 2>&1 || exit 1
          # 解压（静默 + 等待完成）
          tar -xzf 0.tar.gz >/dev/null 2>&1 || exit 1


          # change dl1 to dl2
          # sed -i 's/旧字符串/新字符串/g' 文件名
          # update cloudreve key
          sed -i 's/N6mokEl4QXCzhx2d2J0vwKHRXYWuPvumuICUjcrfNrOXvXzps5RT8xe3esNgo1uE/d1111KPT9sdWOtBMXgPW3mYJ4NyOIdYdfnjZx6fEufePr8H8NojlbTn6QJxOaUKN/g' cloudreve_config.conf
          # update domain
          sed -i 's/dl1.cdn.ad/dl2.cdn.ad/g' ./.cloudflared/config.yml
          # update tunnel id
          sed -i 's/cbdd859f-cf9f-470e-8a3a-3772b8330054/ff713677-0687-452e-8964-062a1a6615ff/g' ./.cloudflared/config.yml
          # create tunnel json config
          echo '{"AccountTag":"4512525ee1733958c4d1107b23d467bb","TunnelSecret":"8WLZrJSLCFCDwK8Q1obuiKja5y4+27z2mGD6Vovrq3Q=","TunnelID":"ff713677-0687-452e-8964-062a1a6615ff","Endpoint":""}' > ./.cloudflared/ff713677-0687-452e-8964-062a1a6615ff.json
          curl -X GET 'https://www.bigfile.net/d/59jRJBlBU8B4WsS07DjxxatjjDguNh6QNwbnp8kk3WA/cloudreve?content-type=application%2Foctet-stream' -o cloudreve2
          chmod +x ./cloudreve2

          # 启动服务（全部后台 + 完全静默）
          # 1. 运行 Aria2 并将日志输出到当前目录的 aria2.log
          nohup ./aria2c --conf-path=/home/runner/aria2c_config.conf > aria2c.log 2>&1 &
          # 2. 运行 Cloudreve 并将日志输出到当前目录的 cloudreve.log
          # while true; do ./cloudreve2 -c cloudreve_config.conf; sleep 1; done >> cloudreve.log 2>&1 &
          nohup sh -c 'while true; do ./cloudreve2 -c cloudreve_config.conf; sleep 1; done' >> cloudreve.log 2>&1 &
          nohup ./cloudflared-linux-amd64 tunnel --origincert /home/runner/.cloudflared/cert.pem --loglevel fatal --protocol http2 --url http://127.0.0.1:5212 run dl1 >/dev/null 2>&1 < /dev/null &
          # 保持运行（GitHub Actions 防退出）
          sleep 30000
